# Copyright Nicolas Paul (2023)
#
# * n@nc0.fr
#
# This software is a computer program whose purpose is to be the personal
# website of Nicolas Paul.
#
# This software is governed by the CeCILL license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and INRIA at the following URL
# "http://www.cecill.info".
#
# As a counterpart to the access to the source code and  rights to copy,
# modify and redistribute granted by the license, users are provided only
# with a limited warranty  and the software's author,  the holder of the
# economic rights,  and the successive licensors  have only  limited
# liability.
#
# In this respect, the user's attention is drawn to the risks associated
# with loading,  using,  modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean  that it is complicated to manipulate,  and  that  also
# therefore means  that it is reserved for developers  and  experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards their
# requirements in conditions enabling the security of their systems and/or
# data to be ensured and,  more generally, to use and operate it in the
# same conditions as regards security.
#
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.

# Nicolas 'nc0' Paul's configuration for the VIM text editor.
# Copyright (c) 2023 Nicolas Paul All rights reserved.
# Use of this configuration is governed by a BSD-style license
# that can be found in the LICENSE file.

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: read
      deployments: write # for status within GitHub
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install NPM deps
        run: npm ci
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: src
          if-no-files-found: error
          retention-days: 60
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: nc0-fr
          directory: src
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
          branch: ${{ github.ref_name }}
  
